ISPF/Controllers/PuestoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;
using ISPF.Models;
using ISPF.AppGestion;
using System.Collections;

namespace ISPF.Controllers
{
    public class PuestoController : Controller
    {
        // GET: api/Puesto
        public ActionResult Index()
        {
            PuestoGestion pu = new PuestoGestion();
            ViewBag.data = pu.mostrarPuestos("");
            return View();
        }

        public JsonResult buscarDepa() {
            departamentoGestion depG = new departamentoGestion();
            ArrayList data = depG.mostrarDepartamentos("");
            return Json(data,JsonRequestBehavior.AllowGet);
        }

        [System.Web.Http.HttpPost]
        public ActionResult insertar(PuestoModelo pu) {
            PuestoGestion puG = new PuestoGestion();
            puG.insertar(pu);
            return View();

        }

        // GET: api/Puesto/5
        public string Get(int id)
        {
            return "value";
        }

        // POST: api/Puesto
        public void Post([FromBody]string value)
        {
        }

        // PUT: api/Puesto/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE: api/Puesto/5
        public void Delete(int id)
        {
        }
    }
}

ISPF/Views/Puesto/Index.cshtml
@model ISPF.Models.PuestoModelo
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<h2>Gestion de Puestos</h2>
<a class="btn btn-primary" href="@Url.Action("insertar","Puesto")">Nuevo</a>
<table class="table">
    <thead>
        <tr>
            <th class="col">Nombre</th>
            <th class="col">Descripci&oacute;n</th>
            <th class="col">Departamento</th>
            <th class="col">Modificar</th>
            <th class="col">Eliminar</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var list in ViewBag.data)
        {
            <tr>
                <td>@list.codigo</td>
                <td>@list.des</td>
                <td>@list.codDep</td>
                <td><a href="@Url.Action("modificar",new {cod=list.codigo})" class="glyphicon glyphicon-edit">Modificar</a></td>
                <td><a href="@Url.Action("eliminar",new { cod=list.codigo})" class="glyphicon glyphicon-trash">Eliminar</a></td>
            </tr>
        }
    </tbody>
</table>

ISPF/Views/Puesto/insertar.cshtml
@model ISPF.Models.PuestoModelo
@{
    ViewBag.Title = "insertar";
}

<h2>Registrar Puesto</h2>

@using (Html.BeginForm())
{
    <div class="form-group">
        <label>Nombre</label>
        @Html.TextBoxFor(model => model.codigo, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Decripci&oacute;n</label>
        @Html.TextAreaFor(model => model.des, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Departamento</label>
        @Html.DropDownListFor(model => model.codDep, new SelectList(""), "--Seleccionar Departamento--", new { @class = "form-control" });
    </div>
    <button type="submit" class="btn btn-primary">Insertar</button>
}
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script>
    $(document).ready(function () {
        $.get("/Puesto/buscarDepa", function (data) {
            $("#codDep").empty();
            $("#codDep").append("<option value='0'>--Selecionar Departamento--</option>");
            $.each(data, function (index, row) {
                $("#codDep").append("<option value=" + row.codigo + ">" + row.codigo + "</option>");
            });

        });
    });

</script>