ISPF/Controllers/DepartamentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;
using ISPF.AppGestion;
using ISPF.Models;

namespace ISPF.Controllers
{
    public class DepartamentoController : Controller
    {
        // GET: api/Departamento
        public ActionResult Index()
        {
            departamentoGestion depG = new departamentoGestion();
            ViewBag.data = depG.mostrarDepartamentos("");
            return View();
        }

        // GET: api/Departamento/5
        [System.Web.Http.HttpPost]
        public ActionResult insertar(DepartamentoModelo dep)
        {
           departamentoGestion depG = new departamentoGestion();
            depG.insertar(dep);
            return View();
        }

        // POST: api/Departamento
        public void Post([FromBody]string value)
        {
        }

        // PUT: api/Departamento/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE: api/Departamento/5
        public void Delete(int id)
        {
        }
    }
}

ISPF/Views/Departamento/Index.cshtml
@model ISPF.Models.DepartamentoModelo
@{
    ViewBag.Title = "departamento";
}

<h2>Gestion de departamentos</h2>

<h2>Vista de Departamentos</h2>
<a class="btn btn-primary" href="@Url.Action("insertar","Departamento")">Nuevo</a>
<table class="table">
    <thead>
        <tr>
            <th class="col">Nombre</th>
            <th class="col">Descipci&oacute;n</th>
            <th class="col">Modificar</th>
            <th class="col">Eliminar</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var list in ViewBag.data)
        {
            <tr>
                <td>@list.codigo</td>
                <td>@list.des</td>
                <td><a href="@Url.Action("modificar",new {cod=list.codigo})" class="glyphicon glyphicon-edit">Modificar</a></td>
                <td><a href="@Url.Action("eliminar",new { cod=list.codigo})" class="glyphicon glyphicon-trash">Eliminar</a></td>
            </tr>
        }
    </tbody>
</table>

ISPF/Views/Departamento/insertar.cshtml
@model ISPF.Models.DepartamentoModelo
@{
    ViewBag.Title = "departamento";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Agregar departamento</h2>

@using (Html.BeginForm())
{
    <div class="form-group">
        <label>Nombre</label>
        @Html.TextBoxFor(model => model.codigo, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Descripci&oacute;n</label>
        @Html.TextAreaFor(model => model.des, new { @class = "form-control" });
    </div>
    <button type="submit" class="btn btn-primary">Insertar</button>
}