ISPF/Controllers/EmpleadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ISPF.AppGestion;
using ISPF.Models;
using System.Collections;
using CrystalDecisions.CrystalReports.Engine;
using ISPF.dataSet;
using System.IO;
using MySql.Data.MySqlClient;

namespace ISPF.Controllers
{
    public class EmpleadoController : Controller
    {
        // GET: api/Empleado
        public ActionResult Index() {

            empleadoGestion emple = new empleadoGestion();
            ViewBag.data = emple.mostrarEmpleados("");
            return View();
        }

        [System.Web.Http.HttpPost]
        public ActionResult insertar(EmpleadoModelo emple)
        {
            empleadoGestion empleG = new empleadoGestion();
            empleG.insertar(emple);
            return View("Index");
        }

        [HttpPost]
        public ActionResult insertarBene(BeneficiarioModelo bene)
        {
            beneficiarioGestion empleG = new beneficiarioGestion();
            empleG.insertar(bene);
            return View("Index");
        }

        public ActionResult insertarBene()
        {
            return View();
        }
        [HttpPost]
        public ActionResult insertarProf(ProfesionalEmModelo prof)
        {
            datosproGestion empleG = new datosproGestion();
            empleG.insertar(prof);
            return View("Index");
        }
        public ActionResult insertarProf(string cod)
        {
   
            return View();
        }

        public JsonResult buscarDepa()
        {
            departamentoGestion depG = new departamentoGestion();
            ArrayList data = depG.mostrarDepartamentos("");
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public ActionResult buscarEmple(string cod)
        {
            empleadoGestion emple = new empleadoGestion();
            ViewBag.data = emple.obtenerEmpleadoDetalle(cod);
            return View(ViewBag.data);
        }

        public JsonResult buscarPuesto(String cod) {
            PuestoGestion pu = new PuestoGestion();
            ArrayList data = pu.mostrarPuestosD(cod);
            return Json(data,JsonRequestBehavior.AllowGet);
        }

        public JsonResult buscarUniversidad(String cod)
        {
            universidadGestion uni = new universidadGestion();
            ArrayList data = uni.mostrarUniversidad("");
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public JsonResult buscarUni()
        {
            universidadGestion u = new universidadGestion();
            ArrayList data = u.mostrarUniversidad("");
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public JsonResult buscarProf(string cod)
        {
            datosproGestion un = new datosproGestion();
            ArrayList data = un.obtenerProf(cod);
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public JsonResult buscarBene(string cod)
        {
            beneficiarioGestion be = new beneficiarioGestion();
            ArrayList data = be.obtenerBeneficiario(cod);
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public ActionResult exportar(string dato) {
            ReportDocument rptr = new ReportDocument();
            rptr.Load(Server.MapPath("~/reporte/empleadoReport.rpt"));
            empleadoGestion empleG = new empleadoGestion();
            MySqlDataAdapter md;
            md = empleG.reporte(dato);
            empleadoDataSet1 eDs = new empleadoDataSet1();
            md.Fill(eDs, "fullEmpleado");
            rptr.SetDataSource(eDs);

            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();
            Stream stream = rptr.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
            stream.Seek(0,SeekOrigin.Begin);
            return File(stream, "application/pdf", "Ficha Empleado.pdf");
        }
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET: api/Empleado/5
        public string Get(int id)
        {
            return "value";
        }

        // POST: api/Empleado
        public void Post([System.Web.Http.FromBody]string value)
        {
        }

        // PUT: api/Empleado/5
        public void Put(int id, [System.Web.Http.FromBody]string value)
        {
        }

        // DELETE: api/Empleado/5
        public void Delete(int id)
        {
        }
    }
}

ISPF/Views/Empleado/Index.cshtml
@model ISPF.Models.EmpleadoModelo
@{
    ViewBag.Title = "empleado";
}

<h2>Empleados</h2>

<h2>Gestion de Empleados</h2>
<a class="btn btn-primary" href="@Url.Action("insertar","Empleado")">Nuevo</a>
<table class="table">
    <thead>
        <tr>
            <th class="col">DPI</th>
            <th class="col">Nombre&oacute;n</th>
            <th class="col">Apellido</th>
            <th class="col">Genero</th>
            <th class="col">Nit</th>
            <th class="col">Puesto</th>
            <th class="col">Agregar Datos</th>
            <th class="col">Agregar Beneficiario</th>
            <th class="col">Detallar</th>
            <th class="col">Modificar</th>
            <th class="col">Eliminar</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var list in ViewBag.data)
        {
        <tr>
            <td>@list.dpi</td>
            <td>@list.nombre</td>
            <td>@list.apellido</td>
            <td>@list.genero</td>
            <td>@list.nit</td>
            <td>@list.puesto</td>
            <td><a href="@Url.Action("insertarProf",new {cod=list.dpi})" class="glyphicon glyphicon-edit">Agregar Datos</a></td>
            <td><a href="@Url.Action("insertarBene",new {cod=list.dpi})" class="glyphicon glyphicon-edit">Agregar Beneficiario</a></td>
            <td><a href="@Url.Action("buscarEmple",new {cod=list.dpi})" class="glyphicon glyphicon-edit">Detallar</a></td>
            <td><a href="@Url.Action("modificar",new {cod=list.dpi})" class="glyphicon glyphicon-edit">Modificar</a></td>
            <td><a href="@Url.Action("eliminar",new { cod=list.dpi})" class="glyphicon glyphicon-trash">Eliminar</a></td>
        </tr>
        }
    </tbody>
</table>

ISPF/Views/Empleado/buscarEmple.cshtml
@model ISPF.Models.EmpleadoModelo
@{
    /**/

    ViewBag.Title = "empleado";
}

<h2>Informacion del Empleado</h2>
<a href="@Url.Action("exportar","Empleado",new {dato=ViewBag.data.dpi })">Exportar Reporte</a><br>
<p class="alert-info">Datos Generales del Empelado</p>

@using (Html.BeginForm())
{
    <div class="form-group">
        <label>DPI</label>
        @Html.TextBoxFor(model => model.dpi, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Nombre</label>
        @Html.TextBoxFor(model => model.nombre, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Apellido</label>
        @Html.TextBoxFor(model => model.apellido, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Fecha de Nacimiento</label>
        @Html.TextBoxFor(model => model.fechaN, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Genero</label>
        @Html.TextBoxFor(model => model.genero, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Direccion</label>
        @Html.TextBoxFor(model => model.direccion, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Codigo de Empleado</label>
        @Html.TextBoxFor(model => model.codigoEmple, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Nit</label>
        @Html.TextBoxFor(model => model.nit, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Correo</label>
        @Html.TextBoxFor(model => model.correo, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Igss</label>
        @Html.TextBoxFor(model => model.igss, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Cuenta Bancaria</label>
        @Html.TextBoxFor(model => model.cuentaBancaria, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Nombre de la madre</label>
        @Html.TextBoxFor(model => model.nomMadre, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Nombre del padre</label>
        @Html.TextBoxFor(model => model.nomPadre, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Nombre del conyugue</label>
        @Html.TextBoxFor(model => model.nomConyugue, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Nivel Educativo</label>
        @Html.TextBoxFor(model => model.nivelAca, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Grado Academico</label>
        @Html.TextBoxFor(model => model.gradoAca, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Puesto</label>
        @Html.TextBoxFor(model => model.puesto, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Fecha de Graducaci&oacute;n</label>
        @Html.TextBoxFor(model => model.fechaGra, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Fecha de Inicio de Labores</label>
        @Html.TextBoxFor(model => model.fechaIngreso, new { @class = "form-control" });
    </div>
}
<br />
<br />
<div class="container">
    <p class="alert-info">Datos profesionales del Empleado</p>
    <form class="body-content">
        <div class="form-group">
            <label>Universidad</label>
            <input type="text" id="uniEmple" name="uniEmpleProf" class="form-control" />
        </div>
        <div class="form-group">
            <label>Codigo Empleado</label>
            <input type="text" name="codEmple" id="codEmpleProf" class="form-control" />
        </div>
        <div class="form-group">
            <label>No. Colegiado</label>
            <input type="text" name="ncole" id="ncoleprof" class="form-control" />
        </div>
        <div class="form-group">
            <label>Fecha Colefiago</label>
            <input type="text" name="fcole" id="fcoleprof" class="form-control" />
        </div>
    </form>
</div>
<br />
<br />
<div class="container">
    <p class="alert-info">Beneficiario</p>
    <div class="form-group">
        <label>Dpi</label>
        <input type="text" name="dpiB" id="dpiB" class="form-control" />
    </div>
    <div class="form-group">
        <label>Nombre</label>
        <input type="text" name="nombreB" id="nombreB" class="form-control" />
    </div>
    <div class="form-group">
        <label>Apellido</label>
        <input type="text" name="apellidoB" id="apellidoB" class="form-control" />
    </div>
    <div class="form-group">
        <label>Fecha de Nacimiento</label>
        <input type="text" name="fechaNB" id="fechaNB" class="form-control" />
    </div>
    <div class="form-group">
        <label>Genero</label>
        <input name="generoB" id="generoB" class="form-control" />
    </div>
    <div class="form-group">
        <label>Direcci&oacute;n</label>
        <input type="text" name="dirB" id="dirB" class="form-control" />
    </div>
    <div class="form-group">
        <label>Parentesco</label>
        <input type="text" name="partentescoB" id="partentescoB" class="form-control" />
    </div>
    <div class="form-group">
        <label>Fecha de Ingreso</label>
        <input type="text" name="fechIngB" id="fechIngB" class="form-control" />
    </div>
    <div class="form-group">
        <label>Codigo Empleado</label>
        <input type="text" name="codigoEmpleBene" id="codigoEmpleBene" class="form-control" />
    </div>
</div>


<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script>
    $(document).ready(function () {
        var dep = $("#dpi").val();
        $.get("/Empleado/buscarProf", { cod: $("#dpi").val() }, function (data) {
            $.each(data, function (index, row) {
                $("#uniEmple").val(row.universidad);
                $("#codEmpleProf").val(dep);
                $("#ncoleprof").val(row.colegiado);
                $("#fcoleprof").val(row.fechaCole);
            });

        });

        $.get("/Empleado/buscarBene", { cod: $("#dpi").val() }, function (data) {
            $.each(data, function (index, row) {
                $("#dpiB").val(row.dpi);
                $("#nombreB").val(row.nombre);
                $("#apellidoB").val(row.apellido);
                $("#fechaNB").val(row.fechaN);
                $("#generoB").val(row.genero);
                $("#dirB").val(row.direccion);
                $("#partentescoB").val(row.parentesco);
                $("#fechIngB").val(row.fechaIgreso);
                $("#codigoEmpleBene").val(dep);
            });

        });


    });
    function reporte() {
        $.get("/Empleado/exportar", { dato: $("#dpi").val() }, function (data) {
            $.each(data, function (index, row) {

            });

        });
        return false;
    }

</script>

ISPF/Views/Empleado/insertar.cshtml
@model ISPF.Models.EmpleadoModelo
@{
    /**/

    ViewBag.Title = "empleado";
}

<h2>Agregar Empleado</h2>
@using (Html.BeginForm())
{
    <div class="form-group">
        <label>DPI</label>
        @Html.TextBoxFor(model => model.dpi, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Nombre</label>
        @Html.TextBoxFor(model => model.nombre, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Apellido</label>
        @Html.TextBoxFor(model => model.apellido, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Fecha de Nacimiento</label>
        @Html.TextBoxFor(model => model.fechaN, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Genero</label>
        <select class="form-control" name="genero">
            <option value="0">--Seleccione Genero--</option>
            <option value="Masculino">Masculino</option>
            <option value="Femenino">Femenino</option>
        </select>
    </div>
    <div class="form-group">
        <label>Direcci&oacute;n</label>
        @Html.TextBoxFor(model => model.direccion, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Nit</label>
        @Html.TextBoxFor(model => model.nit, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Correo</label>
        @Html.TextBoxFor(model => model.correo, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Igss</label>
        @Html.TextBoxFor(model => model.igss, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>No. Cuenta Bancaria</label>
        @Html.TextBoxFor(model => model.cuentaBancaria, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Nombre de la Madre</label>
        @Html.TextBoxFor(model => model.nomMadre, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Nombre del Padre</label>
        @Html.TextBoxFor(model => model.nomPadre, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Nombre del Conyugue</label>
        @Html.TextBoxFor(model => model.nomConyugue, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Nivel Academico</label>
        @Html.TextBoxFor(model => model.nivelAca, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Grado Academico</label>
        @Html.TextBoxFor(model => model.gradoAca, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Departamento</label>
        <select class="form-control" name="depaEmple" id="depaEmple">
            <option value="0">--Seleccione Departamento--</option>
        </select>
    </div>
    <div class="form-group">
        <label>Puesto</label>
        @Html.DropDownListFor(model => model.puesto, new SelectList(""), "--Seleccionar Puesto--", new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Fecha de Graduaci&oacute;n</label>
        @Html.TextBoxFor(model => model.fechaGra, new { @class = "form-control" });
    </div>
    <button type="submit" class="btn btn-primary">Insertar</button>
}

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script>
    $(document).ready(function () {
        $.get("/Empleado/buscarDepa", function (data) {
            $("#depaEmple").empty();
            $("#depaEmple").append("<option value='0'>--Selecionar Departamento--</option>");
            $.each(data, function (index, row) {
                $("#depaEmple").append("<option value=" + row.codigo + ">" + row.codigo + "</option>");
            });

        });

        $("#depaEmple").change(function () {
            $.get("/Empleado/buscarPuesto", { cod: $("#depaEmple").val() }, function (data) {
                $("#puesto").empty();
                $("#puesto").append("<option value='0'>--Seleccionar Puesto--</option>");
                $.each(data, function (index, row) {
                    $("#puesto").append("<option value=" + row.codigo + ">" + row.codigo + "</option>");
                });
            });
        });
    });

    </script>

ISPF/Views/Empleado/insertarBene.cshtml
@model ISPF.Models.BeneficiarioModelo
@{
    /**/

    ViewBag.Title = "insertar Bene";
}

<h2>Insertar Beneficiario</h2>
@using (Html.BeginForm())
{
    <div class="form-group">
        <label>DPI</label>
        @Html.TextBoxFor(model => model.dpi, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Nombre</label>
        @Html.TextBoxFor(model => model.nombre, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Apellido</label>
        @Html.TextBoxFor(modelo => Model.apellido, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Fecha de Nacimiento</label>
        @Html.TextBoxFor(modelo => Model.fechaN, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Genero</label>
        <select class="form-control" name="genero">
            <option value="0">--Seleccione Genero--</option>
            <option value="Masculino">Masculino</option>
            <option value="Femenino">Femenino</option>
        </select>
    </div>
    <div class="form-group">
        <label>Direcci&oacute;n</label>
        @Html.TextBoxFor(modelo => Model.direccion, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Parentesco</label>
        @Html.TextBoxFor(modelo => Model.parentesco, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Codigo del Empleado</label>
        @Html.TextBoxFor(modelo => Model.codigoEmpleP, new { @class = "form-control" });
    </div>
    <button type="submit" class="btn btn-primary">Insertar</button>
}

ISPF/Views/Empleado/insertarProf.cshtml
@model ISPF.Models.ProfesionalEmModelo
@{
    ViewBag.Title = "insertar Prof";
}

<h2>Insertar datos Profecionales</h2>

@using (Html.BeginForm())
{
    <div class="form-group">
        <label>Universidad</label>
        <select class="form-control" name="universidad" id="universidad">
            <option value="0">--Seleccione Universidad--</option>
        </select>
    </div>
    <div class="form-group">
        <label>Codigo del Empleado</label>
        @Html.TextBoxFor(model => model.codigoEmpleado, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Numero de Colegiado</label>
        @Html.TextBoxFor(modelo => Model.colegiado, new { @class = "form-control" });
    </div>
    <div class="form-group">
        <label>Fecha Coelgiado</label>
        @Html.TextBoxFor(modelo => Model.fechaCole, new { @class = "form-control" });
    </div>
    <button type="submit" class="btn btn-primary">Insertar</button>
}

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script>
    $(document).ready(function () {
        $.get("/Empleado/buscarUniversidad", function (data) {
            $("#universidad").empty();
            $("#universidad").append("<option value='0'>--Seleccione Universidad--</option>");
            $.each(data, function (index, row) {
                $("#universidad").append("<option value=" + row.codigo + ">" + row.codigo + "</option>");
            });

        });
    });
</script>